sensirion_common_dir := ./embedded-common
CFLAGS := -Wall -Werror -I. -I${sensirion_common_dir}

common_objects := git_version.o sht_common.o example_usage.o
sw_objects := ${sensirion_common_dir}/sw_i2c/sensirion_sw_i2c.o ${sensirion_common_dir}/sw_i2c/sensirion_sw_i2c_implementation.o
hw_objects := ${sensirion_common_dir}/hw_i2c/sensirion_hw_i2c_implementation.o
all_objects := ${common_objects} ${hw_objects} ${sw_objects} shtc1.o sht3x.o git_version.c

binaries := example_usage_shtc1_sw example_usage_shtc1_hw \
            example_usage_sht3x_sw example_usage_sht3x_hw

.PHONY: FORCE release

git_version.c: FORCE
	git describe --always --dirty | \
		awk 'BEGIN \
		{print "/* THIS FILE IS AUTOGENERATED */"} \
		{print "#include \"git_version.h\""} \
		{print "const char * SHT_DRV_VERSION_STR = \"" $$0"\";"} \
		END {}' > git_version.c

all: ${binaries} release

${sensirion_common_dir}/sw_i2c/sensirion_sw_i2c.o: ${sensirion_common_dir}/sw_i2c/sensirion_sw_i2c.c sht.h \
	${sensirion_common_dir}/sensirion_i2c.h \
	${sensirion_common_dir}/sw_i2c/sensirion_sw_i2c_gpio.h

shtc1.o: git_version.c shtc1.c sht.h ${sensirion_common_dir}/sensirion_i2c.h

sht3x.o: git_version.c sht3x.c sht.h ${sensirion_common_dir}/sensirion_i2c.h

example_usage.o: example_usage.c sht.h

example_usage_shtc1_sw: ${common_objects} ${sw_objects} shtc1.o
	$(CC) $(LDFLAGS) -o $@ $^ $(LOADLIBES) $(LDLIBS)

example_usage_sht3x_sw: ${common_objects} ${sw_objects} sht3x.o
	$(CC) $(LDFLAGS) -o $@ $^ $(LOADLIBES) $(LDLIBS)

example_usage_shtc1_hw: ${common_objects} ${hw_objects} shtc1.o
	$(CC) $(LDFLAGS) -o $@ $^ $(LOADLIBES) $(LDLIBS)

example_usage_sht3x_hw: ${common_objects} ${hw_objects} sht3x.o
	$(CC) $(LDFLAGS) -o $@ $^ $(LOADLIBES) $(LDLIBS)

release: git_version.c
	./release.py && \
	for directory in release/*; do \
		echo $${directory}; \
		cd $${directory}; \
		export subdir="$$(basename $${directory})"; \
		export drv=$${subdir%_*_i2c}; \
		$(CC) $(LDFLAGS) -o example_usage_$${subdir} *.c; \
		$(RM) example_usage_$${subdir}; \
		cd -; \
	done

clean:
	rm -rf ${all_objects} ${binaries} release.pyc release
