#!/bin/bash

set -euo pipefail

mkdir -p shtc1/sw_i2c
cp ../../embedded-common/*.[ch] shtc1/
cp ../../embedded-common/sw_i2c/*.[ch] shtc1/sw_i2c/
cp ../../shtc1/shtc1.[ch] shtc1/
cp ../../sht-common/sht_git_version.h shtc1/
gitversion=$(git describe --always --dirty)
cat << EOF > shtc1/sht_git_version.c
/* THIS FILE IS AUTOGENERATED */
#include "sht_git_version.h"
const char * SHT_DRV_VERSION_STR = "$gitversion";
EOF
